import Header from "@/components/Header";
import "../styles/globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Best kids-school",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={" min-h-screen overflow-x-hidden "}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
